### ISSUE TITLE
Bad dependencies

### ISSUE THREAD

**Issue by iluetkeb** [micro-ROS/rmw_microxrcedds#17]
This package depends on microxrcedds_client, but that package is not a ROS package and can therefore not be found.

**Comment by ZhenshengLee** [comment]
@iluetkeb 

It's in 

https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/243b16b659f1b46e6678db21c30f246910a3b697/CMakeLists.txt#L90

**Comment by iluetkeb** [comment]
This issue is quite old -- I guess we can close it.
