### ISSUE TITLE
Reconnecting to agent after multiple disconnects

### ISSUE THREAD

**Issue by ted-miller** [micro-ROS/rmw_microxrcedds#241]
## Issue template

Industrial robots are generally left on (without rebooting) for very long periods of time. So, I need to be able to detect if the Agent application is terminated on the PC. In that scenario, I shut down the node on the robot and wait for the Agent to come back online. When it does, I'll restart the node with a new connection. (I'm using your ping function to detect the status of the Agent.)

I found that I could do this process twice. But, then it would fail on the third attempt. One of the init functions would return a general error (RMW_RET_ERROR). 

Ultimately, I found that `get_memory()` in [memory.c](https://github.com/micro-ROS/rmw_microxrcedds/blob/51942f621a03a60f932f788a9c262e119dec3f99/rmw_microxrcedds_c/src/memory.c#L34) was returning a NULL. To solve the problem, I simply rebuilt rmw-microxrcedds using `RMW_UXRCE_ALLOW_DYNAMIC_ALLOCATIONS=ON`. 

So, I'm running just fine. But, it makes me suspicious that there is a memory leak.

The issue was discovered on the Motoman robot. But, I was able to reproduce on the PC using the `micro-ros-demos-rclc`.
- Hardware description: PC
- RTOS: Ubuntu
- Installation type: micro_ros_setup
- Version or commit hash: 7670ac9b9ffd4cdb5837e6fd4a7f525f9c043cc7

I modified the `ping_uros_agent` so that it sits in a loop and tries to continually reconnect.
[modified_ping_uros_agent.zip](https://github.com/micro-ROS/rmw_microxrcedds/files/8351592/modified_ping_uros_agent.zip)

#### Steps to reproduce the issue
Setup fresh uros workspace by following the [basic tutorial](https://micro.ros.org/docs/tutorials/core/first_application_linux/).
```
<source galactic>
ted@ted-Ubuntu:~/microros_ws_fresh$ source install/local_setup.bash
ted@ted-Ubuntu:~/microros_ws_fresh$ export RMW_IMPLEMENTATION=rmw_microxrcedds
ted@ted-Ubuntu:~/microros_ws_fresh$ ros2 run micro_ros_demos_rclc ping_uros_agent interactive
```

In another terminal, start the Agent. 
The first terminal will indicate that it is connected. 
After a couple seconds, `ctrl-c` the agent to stop it. 
Wait for the first terminal to indicate that it is looking for the agent. Then restart the agent in the other terminal.
Repeat this process multiple times. 

In this case, it failed on the fifth attempt.

#### Actual behavior

<details><summary>Console output</summary>
<p>

```
ted@ted-Ubuntu:~/microros_ws_fresh$ ros2 run micro_ros_demos_rclc ping_uros_agent interactive
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
[INFO] [1648217900.259890517] []: Created a timer with period 1000 ms.


Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
micro-ROS agent has stopped. Exiting...
Failed status on line 155: 1. Continuing.
Failed status on line 156: 1. Continuing.
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
[INFO] [1648217918.390578284] []: Created a timer with period 1000 ms.


Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
micro-ROS agent has stopped. Exiting...
Failed status on line 155: 1. Continuing.
Failed status on line 156: 1. Continuing.
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
[INFO] [1648217934.513469052] []: Created a timer with period 1000 ms.


Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
micro-ROS agent has stopped. Exiting...
Failed status on line 155: 1. Continuing.
Failed status on line 156: 1. Continuing.
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
[INFO] [1648217947.634014704] []: Created a timer with period 1000 ms.


Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
Agent is still up!

Sent: 'This is a message sent after pinging micro-ROS Agent'

Pinging agent again...
micro-ROS agent has stopped. Exiting...
Failed status on line 155: 1. Continuing.
Failed status on line 156: 1. Continuing.
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
Please, start your micro-ROS Agent first
[rcutils|error_handling.c:65] an error string (message, file name, or formatted message) will be truncated
[ERROR] [1648217962.759251750] [rclc]: [rclc_timer_init_default] Error in rcl_timer_init: error not set, at /home/jenkins-agent/workspace/ci_packaging_linux/ws/src/ros2/rcl/rcl/src/rcl/publisher.c:185, at /home/jenkins-agent/workspace/ci_packaging_linux/ws/src/ros2/rcl/rcl/src/rcl/node.c:384, at /home/jenkins-agent/workspace/ci_packaging_linux/ws/src/ros2/rcl/rcl/src/rcl/publisher.c:185, at /home/jenkins-agent/workspace/ci_packaging_linux/ws/src/ros2/rcl/rcl/src/rcl/node.c:384, at /home/jenkins-agent/workspace/ci_packaging_linux/ws/src/ros2/rcl/rcl/src/rcl/publisher.c:185, at /home/jenkins-agent/workspace/ci_packaging_linux/ws/src/ros2/rcl/rcl/src/rcl/node.c:384, at /home/jenkins-agent/workspace/ci_packaging_linux/ws/src/ros2/rcl/rcl/src/rcl/publisher.c:185, at /home/jenkins-agent/workspace/ci_packaging_linux/ws/src/ros2/rcl/rcl/src/rcl/node.c:3, at /home/jenkins-agent/workspace/ci_packaging_linux/ws/src/ros2/rcl/rcl/src/rcl/guard_condition.c:91

Failed status on line 130: 1. Aborting.
ted@ted-Ubuntu:~/microros_ws_fresh$ 
```

</p>
</details>

#### Additional information
In the console output above, I do see that two of the `fini` functions failed each cycle.
```
Failed status on line 155: 1. Continuing.
Failed status on line 156: 1. Continuing.
```

This corresponds to:
```
            RCSOFTCHECK(rcl_publisher_fini(&publisher, &node));
            RCSOFTCHECK(rcl_node_fini(&node));
```

Perhaps this is the source of the problem. I have not yet traced down those errors. So, I'll start with those functions to determine why they're returning error codes. But, if you have any advice on what else could be the cause, I would love some guidance.

Additionally, if there is something wrong with my approach to "shutting down" after the agent is gone, please let me know.

Thanks!

**Comment by pablogs9** [comment]
I've fixed the example: https://github.com/micro-ROS/micro-ROS-demos/pull/58

Please let us know if  `rcl_timer_fini(&timer);` solves this.

**Comment by pablogs9** [comment]
@Acuadros95 can you take a look at that?

**Comment by Acuadros95** [comment]
> Ultimately, I found that get_memory() in [memory.c](https://github.com/micro-ROS/rmw_microxrcedds/blob/51942f621a03a60f932f788a9c262e119dec3f99/rmw_microxrcedds_c/src/memory.c#L34) was returning a NULL. 

This should not happen, did `rcl_timer_fini(&timer);` solve this?
Please set `RMW_UXRCE_ALLOW_DYNAMIC_ALLOCATIONS=OFF` again and try to replicate this error, as the fini methods should release all the memory blocks.

>  But, from the output, it seems the fini failures are just general errors because the agent is down. Nothing obviously unexpected.

Exactly, `rcl_publisher_fini` and `rcl_node_fini` return `RCL_RET_ERROR` after the destroy operation on the agent timeouts. We should modify this and return `RCL_RET_TIMEOUT` and use the error return for actual memory problems.

You can also set `RMW_UXRCE_ENTITY_DESTROY_TIMEOUT=0` to use best effort communication on the fini methods, which will send the destroy message to the agent, release local resources and return immediately. But its probably better to just ignore this error if blocking time on this methods is not relevant.

> (I am still curious about whether the order of destruction matters.)

It does, but only this limitations apply:
- Destroy a `node` after all its related entities (Publishers, subscribers, services, …) have been destroyed.
- Destroy the `support` object after all the related nodes are destroyed.

**Comment by asasine** [comment]
> > But, from the output, it seems the fini failures are just general errors because the agent is down. Nothing obviously unexpected.
> 
> Exactly, `rcl_publisher_fini` and `rcl_node_fini` return `RCL_RET_ERROR` after the destroy operation on the agent timeouts. We should modify this and return `RCL_RET_TIMEOUT` and use the error return for actual memory problems.

@Acuadros95 was this change ever made?

**Comment by Acuadros95** [comment]
@asasine I am afraid that its not applied.

The timeout stiuation is correctly handle internally at the rmw level. But on the rcl layer, `rcl_publisher_fini` and similar methods will still return `RCL_RET_ERROR` on both cases (Timeout, or actual error).

**Comment by asasine** [comment]
Thanks for getting back to me. Is there any possibility of this change being applied in the future?
